[package]
name = "scemu"
version = "0.1.0"
authors = ["sha0coder <sha0@badchecksum.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.10.0"

