[package]
name = "libscemu"
version = "0.12.9"
edition = "2018"

[dependencies]
iced-x86 = "1.19.0"
uint = "0.9.5"
md5 = "0.7.0"
lazy_static = "1.4.0"
attohttpc = "0.18.0"
rand = "0.8.4"
ctrlc = "3.2.2"
scan_fmt = "0.2.6"
atty = "0.2.14"
chrono = { version = "0.4", features = ["serde"] }
